FROM ubuntu:latest AS builder
RUN apt update -y && \
    apt install -y openjdk-8-jdk && \
    apt install -y maven
COPY . .
RUN mvn -DskipTests package

FROM weaveworksdemos/msd-java:jre-latest

WORKDIR /usr/src/app
#COPY target/*.jar ./app.jar
COPY --from=builder ./target/*.jar ./app.jar

RUN	chown -R ${SERVICE_USER}:${SERVICE_GROUP} ./app.jar

USER ${SERVICE_USER}

ENTRYPOINT ["/usr/local/bin/java.sh","-jar","./app.jar", "--port=80"]
