deploy:
  image:
    name: bitnami/kubectl:latest
    entrypoint: ['']
  script:
    - kubectl config get-contexts
    - kubectl config use-context gitlab-instance-711bf56d/sockshop:k8s-4otus-agent
    - kubectl get pods