stages:
  - build
  - deploy

variables:
  WERF_IMAGES_REPO_MODE: monorepo
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SUBMODULE_DEPTH: 1
  KUBE_NAMESPACE: sockshop

#Build and Publish:
#  stage: build
#  image:
#    name: registry.werf.io/werf/werf:1.2
#  script:
#    - source $(werf ci-env gitlab --as-file)
#    - werf build


Deploy:
  stage: deploy
  image:
    name: registry.werf.io/werf/werf:1.2
  script:
    - source $(werf ci-env gitlab --as-file)
    - werf kubectl config get-contexts
    - werf kubectl config use-context gitlab-instance-711bf56d/sockshop:k8s-4otus-agent
    - werf helm dependency update
    - werf converge --skip-build --set "env_url=$(echo ${CI_ENVIRONMENT_URL} | cut -d / -f 3)"
