stages:
  - build
  - deploy

variables:
  WERF_IMAGES_REPO_MODE: monorepo
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SUBMODULE_DEPTH: 1

Build and Publish:
  stage: build
  image:
#      name: registry.werf.io/werf/werf:1.2
    name: registry.84.201.150.198.sslip.io/gitlab-instance-711bf56d/sockshop/werf-git:1.2
  script:
    - source $(werf ci-env gitlab --as-file)
    - werf build


Deploy:
  stage: deploy
  image:
    name: bitnami/kubectl:latest
    entrypoint: ['']
  script:
    - kubectl config get-contexts
    - kubectl config use-context gitlab-instance-711bf56d/sockshop:k8s-4otus-agent
    - kubectl get pods -A