prometheus:
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: yc-network-hdd
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi
    shards: null
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - prometheus.158.160.45.164.sslip.io

grafana:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"
      cert-manager.io/cluster-issuer: letsencrypt-prod
      cert-manager.io/acme-challenge-type: http01
    hosts:
      - grafana.158.160.45.164.sslip.io
    tls:
    - secretName: grafana.158.160.45.164.sslip.io
      hosts:
        - grafana.158.160.45.164.sslip.io

prometheusOperator:
  admissionWebhooks:
    enabled: false
    patch:
      enabled: false
  tlsProxy:
    enabled: false
  tls:
    enabled: false

alertmanager:
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - alertmanager.158.160.45.164.sslip.io

  storage:
    volumeClaimTemplate:
      spec:
        storageClassName: yc-network-hdd
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
