apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
{{ toYaml .Values.ingress.annotations | indent 4 }}
  labels:
{{ toYaml .Values.ingress.labels | indent 4 }}
  name: {{ template "fullname" .}}-socks-ingress
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: front-end
            port:
              number: 80
        path: /
        pathType: Prefix
#    {{- if .Values.host }}
#    host: {{ template "host" . }}
#    {{- end }}
    host: {{ .Values.global.envUrl }}
#  {{- if .Values.ingress.tlsSecretName }}
  tls:
  - secretName: {{ .Values.global.envUrl }}-tls
#   {{- if .Values.host }}
    hosts:
      - {{ .Values.global.envUrl }}
#   - {{ template "host" . }}
#   {{- end }}
# {{- end }}
